from enum import Enum


class ProposalForm(str, Enum):
    BUILDING_PARAMETERS_BUTTON = "cf01"
    SELECT_NUMBER_FLOORS = "cf02"
    ENTER_BUILT_UP_AREA = "cf03"
    SELECT_FOUNDATION_BUTTON = "cf04"
    SELECT_FOUNDATION_TYPE = "cf05"
    FOUNDATION_TYPES = "cf06"
    SELECT_GROUND_FLOOR_PANELS_TYPE = "cf07"
    SELECT_INTERMEDIATE_FLOOR_TYPE = "cf08"
    SELECT_ATTIC_FLOOR_PANELS_TYPE = "cf09"
    SELECT_EXTERIOR_WALLS_PANELS_TYPE = "cf10"
    SELECT_INTERNAL_PARTITIONS_TYPE = "cf11"
    CONSTRUCTION_TYPES = "cf12"
    SELECT_ROOF_BUTTON = "cf13"
    SELECT_ROOF_TYPE = "cf14"
    SELECT_ROOFING_MATERIAL_BUTTON = "cf15"
    SELECT_ROOFING_MATERIAL = "cf16"
    PRIMORSKY_REGION = "cf17"
    ENTER_BUILDING_ADDRESS = "cf18"
    SELECT_ESTIMATE_TYPE = "cf19"

    def __str__(self) -> str:
        return str.__str__(self)
